### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dznan** [jumpserver/Dockerfile#177]
**JumpServer 版本(v2.19.1)**

**Bug 描述**
lion容器随着运行时间变长，在/opt/lion目录下有大量core.xxx的文件，数量非常大，在docker/overlay2下面会记录大量的更改，占用磁盘空间非常多。在我这里占用了四百多G。完全重启容器才能清除。请问core文件是什么样的文件？能否放在别的映射目录？对容器自身的文件存储，docker都会作大量记录。

**Bug 重现步骤(有截图更好)**
<img width="561" alt="Screenshot 2023-02-23 at 09 57 29" src="https://user-images.githubusercontent.com/21004648/220805517-d3625416-23a9-4ac8-8f77-8886fdb6d18c.png">

**Comment by wojiushixiaobai** [comment]
core dump，程序异常后产生的文件，解决方法的话通过 ulimits.core=0限制文件生成就行
```yaml
...

  lion:
    image: jumpserver/lion:${VERSION}
    container_name: jms_lion
    ulimits:
      core: 0
    restart: always
    tty: true
```
