### ISSUE TITLE
没有找到.env文件

### ISSUE THREAD

**Issue by lacatc** [jumpserver/Dockerfile#57]
![QQ截图20200407105453](https://user-images.githubusercontent.com/37959871/78625382-7f1dcc00-78be-11ea-87c9-8ae609a3cb8b.png)

![QQ截图20200407105612](https://user-images.githubusercontent.com/37959871/78625389-83e28000-78be-11ea-803e-f5ac41fa76bb.png)

**Comment by aurthurxlc** [comment]
自己配置一下即可，示例如下
```toml
Version=1.5.7
DB_HOST=mysql
DB_PORT=3306
DB_USER=jumpserver
DB_PASSWORD=jumpserver
DB_NAME=jumpserver
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=jumpserver
SECRET_KEY=xxx
BOOTSTRAP_TOKEN=jumpserver
```
