### ISSUE TITLE
版本1.5.8和1.5.9无法启动

### ISSUE THREAD

**Issue by leim** [jumpserver/Dockerfile#61]
docker容器方式启动，使用

jumpserver/jms_core
jumpserver/jms_koko
jumpserver/jms_guacamole

启动的时候，redis和mysql都是正常的，但是：

core报错如下，无法启动：
wait for jms_redis ready
koko报错如下：
wait for jms_core ready
guacamole报错如下：
wait for jms_core ready

版本1.5.8和版本1.5.9有如上问题，但是1.5.7启动正常（相同的配置）。

**Comment by wojiushixiaobai** [comment]
@leim 使用的那个docker-compose文件

**Comment by leim** [comment]
配置文件是我自己仿照（`https://github.com/jumpserver/Dockerfile/blob/master/docker-compose.yml`）改的，mysql使用外部数据库，敏感信息已隐去。

从1.5.3版本开始使用jumpserver，`docker-compose.yml` 一路升级至1.5.7，运行一切正常，到继续升级的时候，就出现上面的问题了。


```
version: "3"
services:
  jumpserver:
    image: jumpserver/jms_core:1.5.7
    container_name: jms_core
    restart: always
    hostname: jms
    tty: true
    networks:
      - jms
    environment:
      SECRET_KEY: ******
      BOOTSTRAP_TOKEN: ******
      DB_ENGINE: mysql
      DB_HOST: ******
      DB_PORT: 3306
      DB_USER: ******
      DB_PASSWORD: ******
      DB_NAME: jumpserver
      REDIS_HOST: redis
      TZ: 'Asia/Shanghai'
    volumes:
    - /workplace/media:/opt/jumpserver/data/media
    - /workplace/jms_logs:/opt/jumpserver/logs
  koko:
    image: jumpserver/jms_koko:1.5.7
    container_name: jms_koko
    restart: always
    hostname: koko
    tty: true
    networks:
      - jms
    environment:
      CORE_HOST: http://jumpserver:8080
      BOOTSTRAP_TOKEN: ******
      ACCESS_KEY_FILE: data/keys/access.key
      TZ: 'Asia/Shanghai'
    volumes:
    - /workplace/koko_data:/opt/koko/data
    - /workplace/koko_logs:/opt/koko/logs
    ports:
    - 22222:2222
  guacamole:
    image: jumpserver/jms_guacamole:1.5.7
    container_name: jms_guacamole
    restart: always
    hostname: guacamole
    tty: true
    networks:
      - jms
    environment:
      JUMPSERVER_SERVER: http://jumpserver:8080
      BOOTSTRAP_TOKEN: ******
      JUMPSERVER_KEY_DIR: /config/guacamole/keys
      GUACAMOLE_HOME: /config/guacamole
      TZ: 'Asia/Shanghai'
    volumes:
    - /workplace/gua_keys:/config/guacamole/keys
    - /workplace/gua_logs:/config/guacamole/data/log
  nginx:
    image: nginx:1.17.5
    container_name: jms_nginx
    restart: always
    networks:
      - jms
    volumes:
    - /workplace/static:/work/static
    - /workplace/media:/work/media
    - /workplace/luna:/work/luna
    - /workplace/nginx_conf:/etc/nginx/conf.d
    - /workplace/nginx_logs:/var/log/nginx
    ports:
    - 28080:80
  redis:
    image: redis:5.0.6-alpine
    container_name: jms_redis
    restart: always
    tty: true
    networks:
      - jms
    volumes:
    - /workplace/redis_data:/data

networks:
  jms:
    external:
      name: jms

```
